######################################################################
# Automatically generated by qmake (3.0) Sat Apr 4 17:04:15 2015
######################################################################

TEMPLATE = app
TARGET = sticky
INCLUDEPATH += . src
QT += core gui declarative
CONFIG += c++11

# Input
HEADERS += src/decoration.h src/sticky.h
SOURCES += src/decoration.cpp src/main.cpp src/sticky.cpp
DEPENDPATH += src

# Install
app.path = /usr/local/bin
app.files = sticky
INSTALLS += app